
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Asus
 */
public class CRAPS extends javax.swing.JFrame {

    int sumaDados = 0, valorDado, valorDado2, punto = 0;
    int Monedas = 0, apuesta, por, ganancia;

    public CRAPS() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("CASINO ECCI");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        SALIR3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtmonedas = new javax.swing.JLabel();
        txtganancias = new javax.swing.JLabel();
        txtapuestas = new javax.swing.JLabel();
        txtpor = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        SALIR4 = new javax.swing.JButton();
        SALIR5 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(0, 153, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        jPanel3.setBackground(new java.awt.Color(255, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        SALIR3.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        SALIR3.setText("SALIR");
        SALIR3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALIR3ActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));

        jButton3.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jButton3.setText("Numero");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jButton4.setText("mayor o menor");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jButton6.setText("Directo 11 o 7");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jButton7.setText("pares");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));

        jLabel3.setFont(new java.awt.Font("Bodoni MT", 0, 12)); // NOI18N

        jLabel6.setText("Monedas");

        jLabel7.setText("Apuesta");

        jLabel8.setText("Ganado");

        jLabel9.setText("Multiplicador");

        jLabel10.setText("x");

        txtmonedas.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        txtganancias.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        txtapuestas.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        txtpor.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtganancias, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtmonedas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))
                                .addGap(22, 22, 22))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addComponent(txtapuestas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel10))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9)
                            .addComponent(txtpor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtmonedas, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(txtapuestas, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8))
                            .addComponent(txtpor, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtganancias, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
        );

        jButton9.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jButton9.setText("bajo de 7");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jButton10.setText("sobre 7");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(60, 60, 60)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton4))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton6)
                            .addComponent(jButton7))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton9)
                            .addComponent(jButton10))
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jButton5.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        jButton5.setText("INGRESAR DINERO");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        jButton8.setText("apostar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        SALIR4.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        SALIR4.setText("INFO JUEGO");
        SALIR4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALIR4ActionPerformed(evt);
            }
        });

        SALIR5.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        SALIR5.setText("MENU");
        SALIR5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALIR5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SALIR4)
                        .addGap(18, 18, 18)
                        .addComponent(SALIR5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SALIR3)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SALIR3)
                    .addComponent(jButton5)
                    .addComponent(jButton8)
                    .addComponent(SALIR4)
                    .addComponent(SALIR5))
                .addGap(14, 14, 14))
        );

        jPanel7.setBackground(new java.awt.Color(0, 153, 51));
        jPanel7.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/craps (1).jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel5)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel5)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SALIR3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALIR3ActionPerformed
        JOptionPane.showMessageDialog(null, "!!VUELVE PRONTO¡¡", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/salir.gif"));
        System.exit(0);
    }//GEN-LAST:event_SALIR3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        String numero;

        por = 30;
        txtpor.setText(String.valueOf(por));
        numero = JOptionPane.showInputDialog(null, "Digite el numero al que va a apostar (2-12");
        int numeroD = Integer.parseInt(numero);
        Random r = new Random();
        int valorDado = r.nextInt(6) + 1;
        int valorDado2 = r.nextInt(6) + 1;

        if (valorDado == 1) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 1", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 1.PNG"));
        } else if (valorDado == 2) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 2", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 2.PNG"));
        } else if (valorDado == 3) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 3", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 3.PNG"));
        } else if (valorDado == 4) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 4", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 4.PNG"));
        } else if (valorDado == 5) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 5", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 5.PNG"));
        } else if (valorDado == 6) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 6", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 6.PNG"));
        }

        if (valorDado2 == 1) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 1", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 1.PNG"));
        } else if (valorDado2 == 2) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 2", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 2.PNG"));
        } else if (valorDado2 == 3) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 3", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 3.PNG"));
        } else if (valorDado2 == 4) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 4", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 4.PNG"));
        } else if (valorDado2 == 5) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 5", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 5.PNG"));
        } else if (valorDado2 == 6) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 6", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 6.PNG"));
        }
        sumaDados = valorDado + valorDado2;

        if (sumaDados == numeroD) {
            JOptionPane.showMessageDialog(null, "Ganasteeeee :D", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/fondos.gif"));
            Monedas = Monedas + (apuesta * por);
            txtmonedas.setText(String.valueOf(Monedas));
            ganancia=apuesta * por;
            txtganancias.setText(String.valueOf(ganancia));
            apuesta = 0;
            txtapuestas.setText(String.valueOf(apuesta));
            txtpor.setText(String.valueOf(por));
            
        } else {
            JOptionPane.showMessageDialog(null, "Perdiste todo lo apostado :C", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/papuno.jpg"));

            por = 0;
            Monedas = Monedas + (apuesta * por);
            txtmonedas.setText(String.valueOf(Monedas));
            ganancia=apuesta * por;
            txtganancias.setText(String.valueOf(ganancia));
            apuesta = 0;
            txtapuestas.setText(String.valueOf(apuesta));
            txtpor.setText(String.valueOf(por));
            
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Monedas = Monedas + 100;
        txtmonedas.setText(String.valueOf(Monedas));
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    @SuppressWarnings("empty-statement")
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        por = 10;
        txtpor.setText(String.valueOf(por));
        Random r = new Random();
        int valorDado = r.nextInt(6) + 1;
        int valorDado2 = r.nextInt(6) + 1;
        int sumaDados = valorDado + valorDado2;

        if (valorDado == 1) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 1", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 1.PNG"));
        } else if (valorDado == 2) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 2", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 2.PNG"));
        } else if (valorDado == 3) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 3", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 3.PNG"));
        } else if (valorDado == 4) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 4", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 4.PNG"));
        } else if (valorDado == 5) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 5", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 5.PNG"));
        } else if (valorDado == 6) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 6", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 6.PNG"));
        }

        if (valorDado2 == 1) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 1", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 1.PNG"));
        } else if (valorDado2 == 2) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 2", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 2.PNG"));
        } else if (valorDado2 == 3) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 3", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 3.PNG"));
        } else if (valorDado2 == 4) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 4", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 4.PNG"));
        } else if (valorDado2 == 5) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 5", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 5.PNG"));
        } else if (valorDado2 == 6) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 6", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 6.PNG"));
        }

        if (sumaDados == 2 || sumaDados == 12) {
            JOptionPane.showMessageDialog(null, "Ganasteeeee :D", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/fondos.gif"));
            Monedas = Monedas + (apuesta * por);
            txtmonedas.setText(String.valueOf(Monedas));
            ganancia=apuesta * por;
            txtganancias.setText(String.valueOf(ganancia));
            apuesta = 0;
            txtapuestas.setText(String.valueOf(apuesta));
            txtpor.setText(String.valueOf(por));
            
        } else {
            JOptionPane.showMessageDialog(null, "Perdiste todo lo apostado :C", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/papuno.jpg"));

            por = 0;
            Monedas = Monedas + (apuesta * por);
            txtmonedas.setText(String.valueOf(Monedas));
            ganancia=apuesta * por;
            txtganancias.setText(String.valueOf(ganancia));
            apuesta = 0;
            txtapuestas.setText(String.valueOf(apuesta));
            txtpor.setText(String.valueOf(por));
            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        por = 5;
        txtpor.setText(String.valueOf(por));

        Random r = new Random();
        int valorDado = r.nextInt(6) + 1;
        int valorDado2 = r.nextInt(6) + 1;
        int sumaDados = valorDado + valorDado2;

        if (valorDado == 1) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 1", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 1.PNG"));
        } else if (valorDado == 2) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 2", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 2.PNG"));
        } else if (valorDado == 3) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 3", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 3.PNG"));
        } else if (valorDado == 4) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 4", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 4.PNG"));
        } else if (valorDado == 5) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 5", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 5.PNG"));
        } else if (valorDado == 6) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 6", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 6.PNG"));
        }

        if (valorDado2 == 1) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 1", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 1.PNG"));
        } else if (valorDado2 == 2) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 2", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 2.PNG"));
        } else if (valorDado2 == 3) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 3", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 3.PNG"));
        } else if (valorDado2 == 4) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 4", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 4.PNG"));
        } else if (valorDado2 == 5) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 5", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 5.PNG"));
        } else if (valorDado2 == 6) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 6", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 6.PNG"));
        }
        if (sumaDados == 11 || sumaDados == 7) {

            JOptionPane.showMessageDialog(null, "Ganasteeeee :D", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/fondos.gif"));
            Monedas = Monedas + (apuesta * por);
            txtmonedas.setText(String.valueOf(Monedas));
            ganancia=apuesta * por;
            txtganancias.setText(String.valueOf(ganancia));
            apuesta = 0;
            txtapuestas.setText(String.valueOf(apuesta));
            txtpor.setText(String.valueOf(por));
            

        } else {
            JOptionPane.showMessageDialog(null, "Perdiste todo lo apostado :C", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/papuno.jpg"));

            por = 0;
            Monedas = Monedas + (apuesta * por);
            txtmonedas.setText(String.valueOf(Monedas));
            ganancia=apuesta * por;
            txtganancias.setText(String.valueOf(ganancia));
            apuesta = 0;
            txtapuestas.setText(String.valueOf(apuesta));
            txtpor.setText(String.valueOf(por));
            
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        por = 8;
        txtpor.setText(String.valueOf(por));
        Random r = new Random();
        int valorDado = r.nextInt(6) + 1;
        int valorDado2 = r.nextInt(6) + 1;
        int sumaDados = valorDado + valorDado2;

        if (valorDado == 1) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 1", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 1.PNG"));
        } else if (valorDado == 2) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 2", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 2.PNG"));
        } else if (valorDado == 3) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 3", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 3.PNG"));
        } else if (valorDado == 4) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 4", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 4.PNG"));
        } else if (valorDado == 5) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 5", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 5.PNG"));
        } else if (valorDado == 6) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 6", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 6.PNG"));
        }

        if (valorDado2 == 1) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 1", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 1.PNG"));
        } else if (valorDado2 == 2) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 2", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 2.PNG"));
        } else if (valorDado2 == 3) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 3", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 3.PNG"));
        } else if (valorDado2 == 4) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 4", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 4.PNG"));
        } else if (valorDado2 == 5) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 5", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 5.PNG"));
        } else if (valorDado2 == 6) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 6", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 6.PNG"));
        }

        if (valorDado == 2 && valorDado2 == 2 || valorDado == 3 && valorDado2 == 3 || valorDado == 4 && valorDado2 == 4 || valorDado == 5 && valorDado2 == 5 || valorDado == 6 && valorDado2 == 6
                || valorDado == 1 && valorDado2 == 1) {
            JOptionPane.showMessageDialog(null, "Ganasteeeee :D", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/fondos.gif"));
            Monedas = Monedas + (apuesta * por);
            txtmonedas.setText(String.valueOf(Monedas));
            ganancia=apuesta * por;
            txtganancias.setText(String.valueOf(ganancia));
            apuesta = 0;
            txtapuestas.setText(String.valueOf(apuesta));
            txtpor.setText(String.valueOf(por));
            

        } else {
            JOptionPane.showMessageDialog(null, "Perdiste todo lo apostado :C", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/papuno.jpg"));

            por = 0;
            Monedas = Monedas + (apuesta * por);
            txtmonedas.setText(String.valueOf(Monedas));
            ganancia=apuesta * por;
            txtganancias.setText(String.valueOf(ganancia));
            apuesta = 0;
            txtapuestas.setText(String.valueOf(apuesta));
            txtpor.setText(String.valueOf(por));
            
        }
        ;
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

        if(Monedas ==0){
            JOptionPane.showMessageDialog(null, "Te quedaste sin plata UnU", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/mrwhite.gif"));
        }else {
        Monedas = Monedas - 10;
        apuesta = apuesta + 10;
        txtmonedas.setText(String.valueOf(Monedas));
        txtapuestas.setText(String.valueOf(apuesta));
    }//GEN-LAST:event_jButton8ActionPerformed
    }
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        por = 2;
        txtpor.setText(String.valueOf(por));

        Random r = new Random();
        int valorDado = r.nextInt(6) + 1;
        int valorDado2 = r.nextInt(6) + 1;
        int sumaDados = valorDado + valorDado2;

        if (valorDado == 1) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 1", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 1.PNG"));
        } else if (valorDado == 2) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 2", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 2.PNG"));
        } else if (valorDado == 3) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 3", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 3.PNG"));
        } else if (valorDado == 4) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 4", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 4.PNG"));
        } else if (valorDado == 5) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 5", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 5.PNG"));
        } else if (valorDado == 6) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 6", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 6.PNG"));
        }

        if (valorDado2 == 1) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 1", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 1.PNG"));
        } else if (valorDado2 == 2) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 2", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 2.PNG"));
        } else if (valorDado2 == 3) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 3", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 3.PNG"));
        } else if (valorDado2 == 4) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 4", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 4.PNG"));
        } else if (valorDado2 == 5) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 5", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 5.PNG"));
        } else if (valorDado2 == 6) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 6", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 6.PNG"));
        }

        if (valorDado < 7) {
            JOptionPane.showMessageDialog(null, "Ganasteeeee :D", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/fondos.gif"));
            Monedas = Monedas + (apuesta * por);
            txtmonedas.setText(String.valueOf(Monedas));
            ganancia=apuesta * por;
            txtganancias.setText(String.valueOf(ganancia));
            apuesta = 0;
            txtapuestas.setText(String.valueOf(apuesta));
            txtpor.setText(String.valueOf(por));
            

        } else {
            JOptionPane.showMessageDialog(null, "Perdiste todo lo apostado :C", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/papuno.jpg"));

            por = 0;
            Monedas = Monedas + (apuesta * por);
            txtmonedas.setText(String.valueOf(Monedas));
            ganancia=apuesta * por;
            txtganancias.setText(String.valueOf(ganancia));
            apuesta = 0;
            txtapuestas.setText(String.valueOf(apuesta));
            txtpor.setText(String.valueOf(por));
            
        }
        ;
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

        por = 2;
        txtpor.setText(String.valueOf(por));
        Random r = new Random();
        int valorDado = r.nextInt(6) + 1;
        int valorDado2 = r.nextInt(6) + 1;
        int sumaDados = valorDado + valorDado2;

        if (valorDado == 1) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 1", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 1.PNG"));
        } else if (valorDado == 2) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 2", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 2.PNG"));
        } else if (valorDado == 3) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 3", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 3.PNG"));
        } else if (valorDado == 4) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 4", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 4.PNG"));
        } else if (valorDado == 5) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 5", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 5.PNG"));
        } else if (valorDado == 6) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 6", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 6.PNG"));
        }

        if (valorDado2 == 1) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 1", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 1.PNG"));
        } else if (valorDado2 == 2) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 2", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 2.PNG"));
        } else if (valorDado2 == 3) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 3", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 3.PNG"));
        } else if (valorDado2 == 4) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 4", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 4.PNG"));
        } else if (valorDado2 == 5) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 5", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 5.PNG"));
        } else if (valorDado2 == 6) {
            JOptionPane.showMessageDialog(null, "El primer dado dio : 6", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Dado 6.PNG"));
        }

        if (sumaDados >= 7) {
            JOptionPane.showMessageDialog(null, "Ganasteeeee :D", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/fondos.gif"));
            
            Monedas = Monedas + (apuesta * por);
            txtmonedas.setText(String.valueOf(Monedas));
            ganancia=apuesta * por;
            txtganancias.setText(String.valueOf(apuesta * por));
            apuesta = 0;
            txtapuestas.setText(String.valueOf(apuesta));
            txtpor.setText(String.valueOf(por));
            
            

        } else {
            JOptionPane.showMessageDialog(null, "Perdiste todo lo apostado :C", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/papuno.jpg"));

            por = 0;
            
            Monedas = Monedas + (apuesta * por);
            txtmonedas.setText(String.valueOf(Monedas));
            ganancia=apuesta * por;
            txtganancias.setText(String.valueOf(ganancia));
            apuesta = 0;
            txtapuestas.setText(String.valueOf(apuesta));
            txtpor.setText(String.valueOf(por));
            
            
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void SALIR4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALIR4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SALIR4ActionPerformed

    private void SALIR5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALIR5ActionPerformed
        JOptionPane.showMessageDialog(null,"", "CASINO ECCI" + "...........................Volviendo al menu principal......................", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/MENUVOLVER.gif"));
        MENU formulario = new MENU();
        formulario.setVisible(true);
        dispose();
    }//GEN-LAST:event_SALIR5ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRAPS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRAPS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRAPS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRAPS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRAPS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SALIR3;
    private javax.swing.JButton SALIR4;
    private javax.swing.JButton SALIR5;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel txtapuestas;
    private javax.swing.JLabel txtganancias;
    private javax.swing.JLabel txtmonedas;
    private javax.swing.JLabel txtpor;
    // End of variables declaration//GEN-END:variables
}
