
import java.util.ArrayList;
import java.util.Random;
import java.util.Scanner;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Asus
 */
public class RULETE extends javax.swing.JFrame {

    int valor;
    int punto = 0;
    int Monedas = 0, apuesta, por, ganancia;

    public RULETE() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("CASINO ECCI");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TXTGAN = new javax.swing.JLabel();
        TXTMON = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TXTAPUES = new javax.swing.JLabel();
        SELENUM = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        BOJUGAR = new javax.swing.JButton();
        BOINFOJUEGO = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        BODOC = new javax.swing.JButton();
        BOFIL = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        BOAPOS = new javax.swing.JButton();
        BOINGRE = new javax.swing.JButton();
        BOSAL = new javax.swing.JButton();
        MENU = new javax.swing.JButton();
        BOINFOUS = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));

        jPanel2.setBackground(new java.awt.Color(255, 0, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        jLabel10.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabel10.setText("RULETA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 0)));

        jLabel2.setFont(new java.awt.Font("Stencil", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MONEDAS");

        TXTGAN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TXTGAN.setForeground(new java.awt.Color(255, 204, 0));
        TXTGAN.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 204, 0)));

        TXTMON.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TXTMON.setForeground(new java.awt.Color(255, 255, 255));
        TXTMON.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));

        jLabel7.setFont(new java.awt.Font("Stencil", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 204, 0));
        jLabel7.setText("GANANCIA  OBTENIDA");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(TXTMON, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(TXTGAN, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(78, 78, 78))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TXTMON, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TXTGAN, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RULETACUADROS.PNG"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Stencil", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("APOSTADO");

        TXTAPUES.setForeground(new java.awt.Color(255, 255, 255));
        TXTAPUES.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));

        SELENUM.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        SELENUM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36" }));
        SELENUM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SELENUMActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Stencil", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("SELECCIONE UN NUMERO");

        BOJUGAR.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        BOJUGAR.setText("JUGAR");
        BOJUGAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOJUGARActionPerformed(evt);
            }
        });

        BOINFOJUEGO.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        BOINFOJUEGO.setText("INFO JUEGO");
        BOINFOJUEGO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOINFOJUEGOActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Stencil", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("SELECCIONE UNA DOCENA");

        jLabel12.setFont(new java.awt.Font("Stencil", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("SELECCIONE UNA FILA");

        BODOC.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        BODOC.setText("PRESIONE");
        BODOC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BODOCActionPerformed(evt);
            }
        });

        BOFIL.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        BOFIL.setText("PRESIONE");
        BOFIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOFILActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(BODOC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SELENUM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123)
                .addComponent(BOFIL)
                .addGap(60, 60, 60))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(jLabel12))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TXTAPUES, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BOINFOJUEGO)
                        .addGap(18, 18, 18)
                        .addComponent(BOJUGAR)))
                .addGap(14, 14, 14))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(59, 59, 59))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SELENUM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BOFIL))
                    .addComponent(BODOC))
                .addGap(16, 16, 16)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BOINFOJUEGO)
                        .addComponent(BOJUGAR))
                    .addComponent(TXTAPUES, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 0)));

        BOAPOS.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        BOAPOS.setText("APOSTAR");
        BOAPOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOAPOSActionPerformed(evt);
            }
        });

        BOINGRE.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        BOINGRE.setText("INGRESAR DINERO");
        BOINGRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOINGREActionPerformed(evt);
            }
        });

        BOSAL.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        BOSAL.setText("SALIR");
        BOSAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOSALActionPerformed(evt);
            }
        });

        MENU.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        MENU.setText("MENU");
        MENU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENUActionPerformed(evt);
            }
        });

        BOINFOUS.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        BOINFOUS.setText("INFO USUARIO");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(BOAPOS)
                .addGap(27, 27, 27)
                .addComponent(BOINGRE)
                .addGap(15, 15, 15)
                .addComponent(BOINFOUS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(MENU)
                .addGap(18, 18, 18)
                .addComponent(BOSAL)
                .addGap(22, 22, 22))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BOAPOS)
                    .addComponent(BOINGRE)
                    .addComponent(BOSAL)
                    .addComponent(MENU)
                    .addComponent(BOINFOUS))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ruleta1.gif"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SELENUMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SELENUMActionPerformed
        int N;
        int i = SELENUM.getSelectedIndex();
        if (i == 1) {
            N = 1;
        } else if (i == 2) {
            N = 2;
        } else if (i == 3) {
            N = 3;
        } else if (i == 4) {
            N = 4;
        } else if (i == 5) {
            N = 5;
        } else if (i == 6) {
            N = 6;
        } else if (i == 7) {
            N = 7;
        } else if (i == 8) {
            N = 8;
        } else if (i == 9) {
            N = 9;
        } else if (i == 10) {
            N = 10;
        } else if (i == 11) {
            N = 11;
        } else if (i == 12) {
            N = 12;
        } else if (i == 13) {
            N = 13;
        } else if (i == 14) {
            N = 14;
        } else if (i == 14) {
            N = 14;
        } else if (i == 15) {
            N = 15;
        } else if (i == 16) {
            N = 16;
        } else if (i == 17) {
            N = 17;
        } else if (i == 18) {
            N = 18;
        } else if (i == 19) {
            N = 19;
        } else if (i == 20) {
            N = 20;
        } else if (i == 21) {
            N = 21;
        } else if (i == 22) {
            N = 22;
        } else if (i == 23) {
            N = 23;
        } else if (i == 24) {
            N = 24;
        } else if (i == 25) {
            N = 25;
        } else if (i == 26) {
            N = 26;
        } else if (i == 27) {
            N = 27;
        } else if (i == 28) {
            N = 28;
        } else if (i == 29) {
            N = 29;
        } else if (i == 30) {
            N = 30;
        } else if (i == 31) {
            N = 31;
        } else if (i == 32) {
            N = 32;
        } else if (i == 33) {
            N = 33;
        } else if (i == 34) {
            N = 34;
        } else if (i == 35) {
            N = 35;
        } else if (i == 36) {
            N = 36;
        } else {
            JOptionPane.showMessageDialog(null, "** Seleccione una Opcion **");
        }
    }//GEN-LAST:event_SELENUMActionPerformed

    private void BOSALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOSALActionPerformed
        JOptionPane.showMessageDialog(null, "!!VUELVE PRONTO¡¡", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/salir.gif"));
        System.exit(0);
    }//GEN-LAST:event_BOSALActionPerformed

    private void BOJUGARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOJUGARActionPerformed

        por = 35;
        int i = SELENUM.getSelectedIndex();
        Random r = new Random();
        int valor = r.nextInt(36) + 1;

        if (valor == 1) {
            JOptionPane.showMessageDialog(null, "El numero obtenido es: 1", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/ruletanum.GIF"));
        } else if (valor == 2) {
            JOptionPane.showMessageDialog(null, "El numero obtenido es: 2", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/ruletanum.GIF"));
        } else if (valor == 3) {
            JOptionPane.showMessageDialog(null, "El numero obtenido es: 3", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/ruletanum.GIF"));
        } else if (valor == 4) {
            JOptionPane.showMessageDialog(null, "El numero obtenido es: 4", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/ruletanum.GIF"));
        } else if (valor == 5) {
            JOptionPane.showMessageDialog(null, "El numero obtenido es: 5", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/ruletanum.GIF"));
        } else if (valor == 6) {
            JOptionPane.showMessageDialog(null, "El numero obtenido es: 6", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/ruletanum.GIF"));
        } else if (valor == 7) {
            JOptionPane.showMessageDialog(null, "El numero obtenido es: 7", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/ruletanum.GIF"));
        } else if (valor == 8) {
            JOptionPane.showMessageDialog(null, "El numero obtenido es: 8", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/ruletanum.GIF"));
        } else if (valor == 9) {
            JOptionPane.showMessageDialog(null, "El numero obtenido es: 9", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/ruletanum.GIF"));
        } else if (valor == 10) {
            JOptionPane.showMessageDialog(null, "El numero obtenido es: 10", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/ruletanum.GIF"));
        } else if (valor == 11) {
            JOptionPane.showMessageDialog(null, "El numero obtenido es: 11", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/ruletanum.GIF"));
        } else if (valor == 12) {
            JOptionPane.showMessageDialog(null, "El numero obtenido es: 12", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/ruletanum.GIF"));
        } else if (valor == 13) {
            JOptionPane.showMessageDialog(null, "El numero obtenido es: 13", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/ruletanum.GIF"));
        } else if (valor == 14) {
            JOptionPane.showMessageDialog(null, "El numero obtenido es: 14", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/ruletanum.GIF"));
        } else if (valor == 15) {
            JOptionPane.showMessageDialog(null, "El numero obtenido es: 15", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/ruletanum.GIF"));
        } else if (valor == 16) {
            JOptionPane.showMessageDialog(null, "El numero obtenido es: 16", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/ruletanum.GIF"));
        } else if (valor == 17) {
            JOptionPane.showMessageDialog(null, "El numero obtenido es: 17", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/ruletanum.GIF"));
        } else if (valor == 18) {
            JOptionPane.showMessageDialog(null, "El numero obtenido es: 18", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/ruletanum.GIF"));
        } else if (valor == 19) {
            JOptionPane.showMessageDialog(null, "El numero obtenido es: 19", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/ruletanum.GIF"));
        } else if (valor == 20) {
            JOptionPane.showMessageDialog(null, "El numero obtenido es: 20", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/ruletanum.GIF"));
        } else if (valor == 21) {
            JOptionPane.showMessageDialog(null, "El numero obtenido es: 21", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/ruletanum.GIF"));
        } else if (valor == 22) {
            JOptionPane.showMessageDialog(null, "El numero obtenido es: 22", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/ruletanum.GIF"));
        } else if (valor == 23) {
            JOptionPane.showMessageDialog(null, "El numero obtenido es: 23", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/ruletanum.GIF"));
        } else if (valor == 24) {
            JOptionPane.showMessageDialog(null, "El numero obtenido es: 24", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/ruletanum.GIF"));
        } else if (valor == 25) {
            JOptionPane.showMessageDialog(null, "El numero obtenido es: 25", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/ruletanum.GIF"));
        } else if (valor == 26) {
            JOptionPane.showMessageDialog(null, "El numero obtenido es: 26", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/ruletanum.GIF"));
        } else if (valor == 27) {
            JOptionPane.showMessageDialog(null, "El numero obtenido es: 27", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/ruletanum.GIF"));
        } else if (valor == 28) {
            JOptionPane.showMessageDialog(null, "El numero obtenido es: 28", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/ruletanum.GIF"));
        } else if (valor == 29) {
            JOptionPane.showMessageDialog(null, "El numero obtenido es: 29", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/ruletanum.GIF"));
        } else if (valor == 30) {
            JOptionPane.showMessageDialog(null, "El numero obtenido es: 30", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/ruletanum.GIF"));
        } else if (valor == 31) {
            JOptionPane.showMessageDialog(null, "El numero obtenido es: 31", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/ruletanum.GIF"));
        } else if (valor == 32) {
            JOptionPane.showMessageDialog(null, "El numero obtenido es: 32", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/ruletanum.GIF"));
        } else if (valor == 33) {
            JOptionPane.showMessageDialog(null, "El numero obtenido es: 33", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/ruletanum.GIF"));
        } else if (valor == 34) {
            JOptionPane.showMessageDialog(null, "El numero obtenido es: 34", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/ruletanum.GIF"));
        } else if (valor == 35) {
            JOptionPane.showMessageDialog(null, "El numero obtenido es: 35", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/ruletanum.GIF"));
        } else if (valor == 36) {
            JOptionPane.showMessageDialog(null, "El numero obtenido es: 36", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/ruletanum.GIF"));
        }

        if (valor == i) {
            JOptionPane.showMessageDialog(null, "Ganasteeeee :D", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/fondos.gif"));

            Monedas = Monedas + (apuesta * por);
            TXTMON.setText(String.valueOf(Monedas));
            ganancia = apuesta * por;
            TXTGAN.setText(String.valueOf(apuesta * por));
            apuesta = 0;
            TXTAPUES.setText(String.valueOf(apuesta));

        } else {
            JOptionPane.showMessageDialog(null, "Perdiste todo lo apostado :C", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/PERDER.GIF"));

            por = 0;

            Monedas = Monedas + (apuesta * por);
            TXTMON.setText(String.valueOf(Monedas));
            ganancia = apuesta * por;
            TXTGAN.setText(String.valueOf(ganancia));
            apuesta = 0;
            TXTAPUES.setText(String.valueOf(apuesta));
        }


    }//GEN-LAST:event_BOJUGARActionPerformed

    private void BOAPOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOAPOSActionPerformed
        if (Monedas == 0) {
            JOptionPane.showMessageDialog(null, "Te quedaste sin plata UnU", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/mrwhite.gif"));
        } else {
            Monedas = Monedas - 10;
            apuesta = apuesta + 10;
            TXTMON.setText(String.valueOf(Monedas));
            TXTAPUES.setText(String.valueOf(apuesta));
        }
    }//GEN-LAST:event_BOAPOSActionPerformed

    private void MENUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENUActionPerformed
        JOptionPane.showMessageDialog(null, "", "CASINO ECCI" + "...........................Volviendo al menu principal......................", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/MENUVOLVER.gif"));
        MENU formulario = new MENU();
        formulario.setVisible(true);
        dispose();
    }//GEN-LAST:event_MENUActionPerformed

    private void BODOCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BODOCActionPerformed

        String numero;
        int x = 0;

        por = 2;
        numero = JOptionPane.showInputDialog(null, "Digite el numero de la docena 1-3");
        int numeroD = Integer.parseInt(numero);
        Random r = new Random();
        int valor = r.nextInt(36) + 1;

        if (valor >= 1 && valor <= 12) {
            x = 1;
            JOptionPane.showMessageDialog(null, "El numero obtenido se encuentra en la docena numero 1 y es: " + valor, "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/ruletanum.GIF"));
        } else if (valor >= 13 && valor <= 24) {
            x = 2;
            JOptionPane.showMessageDialog(null, "El numero obtenido se encuentra en la docena numero 2 y es: " + valor, "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/ruletanum.GIF"));
        } else if (valor >= 14 && valor <= 36) {
            x = 3;
            JOptionPane.showMessageDialog(null, "El numero obtenido se encuentra en la docena numero 3 y es: " + valor, "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/ruletanum.GIF"));
        }

        if (numeroD == x) {
            JOptionPane.showMessageDialog(null, "Ganasteeeee :D", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/fondos.gif"));
            Monedas = Monedas + (apuesta * por);
            TXTMON.setText(String.valueOf(Monedas));
            ganancia = apuesta * por;
            TXTGAN.setText(String.valueOf(ganancia));
            apuesta = 0;
            TXTAPUES.setText(String.valueOf(apuesta));

        } else {
            JOptionPane.showMessageDialog(null, "Perdiste todo lo apostado :C", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/PERDER.GIF"));

            por = 0;
            Monedas = Monedas + (apuesta * por);
            TXTMON.setText(String.valueOf(Monedas));
            ganancia = apuesta * por;
            TXTGAN.setText(String.valueOf(ganancia));
            apuesta = 0;
            TXTAPUES.setText(String.valueOf(apuesta));

        }
    }//GEN-LAST:event_BODOCActionPerformed

    private void BOFILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOFILActionPerformed
        String numero;
        int x = 0;

        por = 2;
        numero = JOptionPane.showInputDialog(null, "Digite el numero de columna que desea 1-3");
        int[] col3 = new int[]{3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36};
        int[] col2 = new int[]{2, 5, 8, 11, 14, 17, 20, 23, 26, 29, 32, 35};
        int[] col1 = new int[]{1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34};
        int numeroD = Integer.parseInt(numero);
        Random r = new Random();
        int valor = r.nextInt(36) + 1;

        for (int i = 0; i < col3.length; i++) {
            if (valor == col3[i]) {
                x = 3;
                JOptionPane.showMessageDialog(null, "El numero obtenido se encuentra en la columna 1 y es: " + valor, "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/ruletanum.GIF"));
            } else;
        }
        for (int i = 0; i < col2.length; i++) {
            if (valor == col2[i]) {
                x = 2;
                JOptionPane.showMessageDialog(null, "El numero obtenido se encuentra en la columna 2 y es: " + valor, "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/ruletanum.GIF"));
            } else;
        }
        for (int i = 0; i < col1.length; i++) {
            if (valor == col1[i]) {
                x = 1;
                JOptionPane.showMessageDialog(null, "El numero obtenido se encuentra en la columna 3 y es: " + valor, "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/ruletanum.GIF"));
            } else;
        }

        if (numeroD == x) {
            JOptionPane.showMessageDialog(null, "Ganasteeeee :D", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/fondos.gif"));
            Monedas = Monedas + (apuesta * por);
            TXTMON.setText(String.valueOf(Monedas));
            ganancia = apuesta * por;
            TXTGAN.setText(String.valueOf(ganancia));
            apuesta = 0;
            TXTAPUES.setText(String.valueOf(apuesta));

        } else {
            JOptionPane.showMessageDialog(null, "Perdiste todo lo apostado :C", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/PERDER.GIF"));

            por = 0;
            Monedas = Monedas + (apuesta * por);
            TXTMON.setText(String.valueOf(Monedas));
            ganancia = apuesta * por;
            TXTGAN.setText(String.valueOf(ganancia));
            apuesta = 0;
            TXTAPUES.setText(String.valueOf(apuesta));

        }

    }//GEN-LAST:event_BOFILActionPerformed

    private void BOINFOJUEGOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOINFOJUEGOActionPerformed
        JOptionPane.showMessageDialog(null, "El juego de la ruleta consiste en que gira y escoge un numero de 36 que es el que gana,"
                + "\n" + "se pueden escoger una de las tres opciones en las cuales si el numero cae se ganara"
                + "\n" + "la apuesta dependiendo de su multiplicador, las cuales son: "
                + "\n" + "1.Seleccionar una de las tres docenas (2 a 1)"
                + "\n" + "2.Seleccioanr un numero de los 36 (35 a 1)"
                + "\n" + "3. Seleccionar una de las tres columnas (2 a 1)", "CASINO ECCI", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/informacion.gif"));
    }//GEN-LAST:event_BOINFOJUEGOActionPerformed

    private void BOINGREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOINGREActionPerformed
        Monedas = Monedas + 100;
        TXTMON.setText(String.valueOf(Monedas));
    }//GEN-LAST:event_BOINGREActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RULETE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RULETE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RULETE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RULETE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RULETE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BOAPOS;
    private javax.swing.JButton BODOC;
    private javax.swing.JButton BOFIL;
    private javax.swing.JButton BOINFOJUEGO;
    private javax.swing.JButton BOINFOUS;
    private javax.swing.JButton BOINGRE;
    private javax.swing.JButton BOJUGAR;
    private javax.swing.JButton BOSAL;
    private javax.swing.JButton MENU;
    private javax.swing.JComboBox<String> SELENUM;
    private javax.swing.JLabel TXTAPUES;
    private javax.swing.JLabel TXTGAN;
    private javax.swing.JLabel TXTMON;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
